In [26]:
#Q1>

import numpy as np
arr= np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [6]:
#Q2>

lst1=[]
lst2=[]
for i in range(5):
    lst1.append(input())
for i in range(5):
    lst2.append(input())
arr1=np.array(lst1)
arr2=np.array(lst2)
arr=np.concatenate((arr1, arr2), axis=0)
print(arr)
print(np.sort(arr))

10
23
51
20
02
01
65
75
25
45
['10' '23' '51' '20' '02' '01' '65' '75' '25' '45']
['01' '02' '10' '20' '23' '25' '45' '51' '65' '75']


In [4]:
#Q3>

print(np.ndim(arr)) #code to find dimension
print(np.size(arr)) #code to find size

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
2
9


In [11]:
#Q4>

arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr.reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [22]:
arr1=np.arange(1,10)
arr2=np.arange(11,20)
arr_1=arr1.reshape(3,3)
arr_2=arr2.reshape(3,3)
a=np.vstack((arr_1,arr_2))
b=np.hstack((arr_1,arr_2))
print(a)
print()
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [25]:
a=np.array([1,2,5,4,5,4,3,8,2,6,5])
b=np.unique(a) #use numpy.unique() to get unique items
c=np.size(b) #use numpy.size() on unique item array to get counts of unique items
print(b)
print(c)

[1 2 3 4 5 6 8]
7
